07_Mvc_Crud_Doctores_Ado/Models/Doctor.cs
namespace _07_Mvc_Crud_Doctores_Ado.Models
{
    public class Doctor
    {
        public string HospitalCod { get; set; }
        public string DoctorNum { get; set; }
        public string Apellido { get; set; }
        public string Especialidad { get; set; }
        public int Salario { get; set; }
    }
}

07_Mvc_Crud_Doctores_Ado/Models/DoctoresHospitales.cs
namespace _07_Mvc_Crud_Doctores_Ado.Models
{
    public class DoctoresHospitales
    {

    }
}

07_Mvc_Crud_Doctores_Ado/Models/ErrorViewModel.cs
namespace _07_Mvc_Crud_Doctores_Ado.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

07_Mvc_Crud_Doctores_Ado/Models/Hospital.cs
namespace _07_Mvc_Crud_Doctores_Ado.Models
{
    public class Hospital
    {
        public string HospitalCod { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string NumCama { get; set; }
    }
}

07_Mvc_Crud_Doctores_Ado/Controllers/DoctoresController.cs
using _07_Mvc_Crud_Doctores_Ado.Models;
using _07_Mvc_Crud_Doctores_Ado.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace _07_Mvc_Crud_Doctores_Ado.Controllers
{
    public class DoctoresController : Controller
    {
        RepositoryDoctores repo;

        public DoctoresController()
        {
            this.repo = new RepositoryDoctores();
        }

        public IActionResult Index()
        {
            List<Doctor> doctores = this.repo.GetDoctores();

            return View(doctores);
        }

        public IActionResult Create()
        {
            List<Doctor> doctores = this.repo.GetDoctores();

            List<Hospital> hospitales = this.repo.GetHospitales();
            ViewData["Hospitales"] = hospitales;

            string maxDoctorNum = this.repo.GetMaxNumDoctor();
            ViewData["Max"] = maxDoctorNum;

            return View(doctores);
        }

        [HttpPost]
        public IActionResult Create(Doctor doctor)
        {
           this.repo.CreateDoctores(doctor.HospitalCod, doctor.DoctorNum, doctor.Apellido, doctor.Especialidad, doctor.Salario);

            return RedirectToAction("Index");
        }

        public IActionResult Details(string doctorNum)
        {
            Doctor doctor = this.repo.FindDoctor(doctorNum);

            return View(doctor);
        }

        public IActionResult Delete(string doctorNum)
        {
            this.repo.DeleteDoctores(doctorNum);

            return RedirectToAction("Index");
        }

        public IActionResult Update(string doctorNum)
        {
            Doctor doctor = this.repo.FindDoctor(doctorNum);

            return View(doctor);
        }

        [HttpPost]
        public IActionResult Update(Doctor doctor)
        {
            this.repo.UpdateDoctor(doctor.HospitalCod, doctor.Apellido, doctor.Especialidad, doctor.Salario, doctor.DoctorNum);

            return RedirectToAction("Index");
        }
    }
}

07_Mvc_Crud_Doctores_Ado/Controllers/HomeController.cs
using _07_Mvc_Crud_Doctores_Ado.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace _07_Mvc_Crud_Doctores_Ado.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

07_Mvc_Crud_Doctores_Ado/Views/Doctores/Create.cshtml
@model List<Doctor>

@{
    List<Hospital> hospitales = ViewData["Hospitales"] as List<Hospital>;
    string max = ViewData["Max"] as string;
}

<h1>Crear Doctor</h1>

<form method="post">
    <label>Hospital</label>
    <select name="hospitalCod" class="form-select">
        @foreach(Hospital hospi in hospitales)
        {
            <option value="@hospi.HospitalCod">@hospi.Nombre</option>
        }
    </select>

    <label>Numero del doctor</label>
    <input type="text" name="doctorNum" class="form-control" value="@max" />

    <label>Apellido</label>
    <input type="text" name="apellido" class="form-control" />
    
    <label>Especialidad</label>
    <select name="especialidad" class="form-select">
        @foreach (Doctor doc in Model)
        {
                <option value="@doc.Especialidad">@doc.Especialidad</option>
        }
    </select>

    <label>Salario</label>
    <input type="number" name="salario" class="form-control" />

    <button type="submit" class="btn btn-success">Crear doctor</button>
</form>

07_Mvc_Crud_Doctores_Ado/Views/Doctores/Details.cshtml
@model Doctor

<h1>Detalles del doctor</h1>

<ul>
    <li>@Model.Apellido</li>
    <li>@Model.Especialidad</li>
    <li>@Model.Salario</li>
</ul>

07_Mvc_Crud_Doctores_Ado/Views/Doctores/Index.cshtml
@model List<Doctor>

<h1>Vista inicial Doctores</h1>

@if(Model !=  null) {
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Hospital Cod</th>
                <th>Num Doctor</th>
                <th>Apellido</th>
                <th>Especialidad</th>
                <th>Salario</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(Doctor doc in Model) {
                <tr>
                    <td>@doc.HospitalCod</td>
                    <td>@doc.DoctorNum</td>
                    <td>@doc.Apellido</td>
                    <td>@doc.Especialidad</td>
                    <td>@doc.Salario</td>
                    <td>
                        @Html.ActionLink("Details", "Details", "Doctores", new{ doctorNum = doc.DoctorNum }) |
                        @Html.ActionLink("Delete", "Delete", "Doctores", new{ doctorNum = doc.DoctorNum }) |
                        @Html.ActionLink("Update", "Update", "Doctores", new{ doctorNum = doc.DoctorNum })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

07_Mvc_Crud_Doctores_Ado/Views/Doctores/Update.cshtml
@model Doctor

<h1>Modificar doctor</h1>

<form method="post">
    <label>Hospital</label>
    <input type="text" name="hospitalCod" class="form-control" value="@Model.HospitalCod" />

    <input type="hidden" name="doctorNum" class="form-control" value="@Model.DoctorNum" />

    <label>Apellido</label>
    <input type="text" name="apellido" class="form-control" value="@Model.Apellido" />

    <label>Especialidad</label>
    <input type="text" name="especialidad" class="form-control" value="@Model.Especialidad" />

    <label>Salario</label>
    <input type="number" name="salario" class="form-control" value="@Model.Salario" />

    <button type="submit" class="btn btn-info">Actualizar doctor</button>
</form>

07_Mvc_Crud_Doctores_Ado/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

07_Mvc_Crud_Doctores_Ado/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _07_Mvc_Crud_Doctores_Ado</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_07_Mvc_Crud_Doctores_Ado.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_07_Mvc_Crud_Doctores_Ado</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctores" asp-action="Index">Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctores" asp-action="Create">Crear Departamento</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - _07_Mvc_Crud_Doctores_Ado - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>